apiVersion: v1
kind: Service
metadata:
  labels:
    streaming-service: api
  name: api
  namespace: streaming-service-app
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    streaming-service: api