apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: streaming-service-app
  labels:
    streaming-service: frontend
spec:
  selector:
    streaming-service: frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
